### PR TITLE
Fix camel case inconsistency

### LINKED ISSUE #224: Code generated for screaming-case enum names conflicts with built_value
```
  [SEVERE] built_value_generator:built_value on lib/src/api/graphql/schema/schema.schema.gql.dart (cached):
  Error in BuiltValueGenerator for /glucose/lib/src/api/graphql/schema/schema.schema.gql.dart.
  Please make the following changes to use built_value serialization:  1. Declare GENUM_EVENTLOG_EVENTTYPE.serializer as: static Serializer<GENUM_EVENTLOG_EVENTTYPE> get serializer => _$gENUMEVENTLOGEVENTTYPESerializer; got static Serializer<GENUM_EVENTLOG_EVENTTYPE> get serializer => _$genumEventlogEventtypeSerializer;
  2. Declare GENUM_EVENTLOG_EXERCISETYPE.serializer as: static Serializer<GENUM_EVENTLOG_EXERCISETYPE> get serializer => _$gENUMEVENTLOGEXERCISETYPESerializer; got static Serializer<GENUM_EVENTLOG_EXERCISETYPE> get serializer => _$genumEventlogExercisetypeSerializer;
  3. Declare GENUM_EVENTLOG_MEALTYPE.serializer as: static Serializer<GENUM_EVENTLOG_MEALTYPE> get serializer => _$gENUMEVENTLOGMEALTYPESerializer; got static Serializer<GENUM_EVENTLOG_MEALTYPE> get serializer => _$genumEventlogMealtypeSerializer;
  [SEVERE] Failed after 4.6s
  pub finished with exit code 1
  ```
  These enum names come from strapi.io and can not be influenced except by changing Strapi code

ferry: 0.9.4
built_value: 7.1.0

### PR DESCRIPTION
**Pull request by smkhalsa**
fixes #224

### CODE REVIEW

**Comment by vishalrao8** [comment]
How can one use your fix without it being merged into master and released on pub dev. And I am using ferry_generator which depends on gql_code_builder so I have not explicitly added this library as it's already a dependency for ferry.

**Comment by smkhalsa** [comment]
@vishalrao8 I just rebased, so you should be able to set a dependency override on this PR's commit.

I've been having issues with multipack which is causing some tests to fail.

Once https://github.com/gql-dart/gql/pull/192 is merged, I should be able to merge this.

**Comment by vishalrao8** [comment]
I can't find any way to put dependency override for this particular PR in pubspec.yaml file.

**Comment by aquadesk** [comment]
pull this repo in your local and do 
```
dependency_overrides:
  gql_code_builder:
    path: ../../../gql/codegen/gql_code_builder

```

**Pull request merged**
