### PR TITLE
Merge in dio link

### PR DESCRIPTION
**Pull request by klavs**
Adopt `gql_dio_link` and welcome @TarekkMA as a contributor.

### CODE REVIEW

**Comment by klavs** [comment]
@TarekkMA, please check why tests are failing

**Comment by TarekkMA** [comment]
I have fixed the issues with the tests, but the svg check don't know how to solve it.

**Comment by klavs** [comment]
Thanks, I'll fix the svg

**Comment by klavs** [comment]
@TarekkMA, I moved the example to the main examples directory and replaced it by a readme file.

**Review by TarekkMA — APPROVED** [review]
LGTM :rocket:

**Pull request merged**
