### PR TITLE
gql_websocket_link: Delay requests until connect is done

### PR DESCRIPTION
**Pull request by janosroden**
If `initialPayload` is an async function then wait for it before send any requests.
For example acquire a JWT token.

### CODE REVIEW

**Comment by janosroden** [comment]
@agent3bood Could you please take a look?

**Comment by agent3bood** [comment]
Will check it.

Why are there changes to `gql.svg` there is another PR with an issue with the svg. Did you modify it or is it auto generated?

**Comment by janosroden** [comment]
It's validated by CI build (I copied it from the logs)

**Comment by agent3bood** [comment]
The code should await for the websocket to open before sending any request.

Can you try another way of fixing the issue you are facing.

1.
Remove the `.startWith(open)` from here `waitForConnectedState`

```
      final Stream<int> waitForConnectedState = _connectionStateController
          .where((state) => state == open)
          .take(1);
```

https://github.com/gql-dart/gql/blob/master/links/gql_websocket_link/lib/src/link.dart#L113

2.
in `_connect()`

move the `_connectionStateController.value = open;` to after sending the initial payload 

```
if (initialPayload is Function) {
        final dynamic payload = await initialPayload();
        _write(InitOperation(payload));
      } else {
        _write(InitOperation(initialPayload));
      }
_connectionStateController.value = open;
```

**Comment by agent3bood** [comment]
@janosroden  Did my solution fix the issue for you?

**Comment by janosroden** [comment]
@agent3bood Yes, I just tried, your solution works perfectly. Thanks.

**Review by agent3bood — APPROVED** [review]
LGTM

**Pull request merged**
