### PR TITLE
fix #186 #188

### LINKED ISSUE #186: [feature] update rxdart(in gql_websocker_link) to 0.25.0
https://github.com/gql-dart/ferry/issues/148
now, gql_websocker_link is mismatch with ferry.

### PR DESCRIPTION
**Pull request by huang12zheng**

### CODE REVIEW

**Comment by agent3bood** [comment]
Thanks for the PR, would you update the package version to `0.1.6` & update the `CHANGELOG`.

**Comment by huang12zheng** [comment]
@agent3bood 
I don't know what's going on SVG. Can you give me a hand?

**Comment by agent3bood** [comment]
Not sure about the SVG error. But why did you add `  gql: ^0.12.3` to the dependencies?

**Comment by huang12zheng** [comment]
I never add `gql: ^0.12.3`, It's there. 
I just sort it due to IDE error.

you can check https://github.com/gql-dart/gql/blob/master/links/gql_websocket_link/pubspec.yaml

**Comment by agent3bood** [comment]
To solve the svg issue, copy then ew generated svg from CI https://github.com/gql-dart/gql/pull/189/checks?check_run_id=1866275604

**Comment by huang12zheng** [comment]
I just use V0.1.6 due to change is mix.

**Review by agent3bood — APPROVED** [review]
LGTM

**Comment by agent3bood** [comment]
@huang12zheng Thanks for contributing to this project, all looks OK.
Since the version 0.1.6 is out, please upgrade to 0.1.7.

**Comment by huang12zheng** [comment]
> I just use V0.1.6 due to change is mix.

OK, I would do it to V0.1.7

**Review by agent3bood — APPROVED** [review]
LGTM

**Pull request merged**
