### PR TITLE
Update analyzer version

### PR DESCRIPTION
**Pull request by lucaspal**
Update the `analyzer` package from `^0.39.14` to `^0.40.4`.

Advantages: 
- Quite some open issues are fixed
- `gql_code_builder` would be now compatible with the latest version of `build_runner` (^1.10.3)

EDIT: This PR is blocked, waiting for the new release of `build_value_generator`.  More info [here](https://github.com/gql-dart/gql/pull/155/files#diff-851e03fed93b2f4ed433bee31569ad83bfb570ca4ba35f639de67e37a166c5fdR17)

### CODE REVIEW

**Comment by codiyer** [comment]
Do we have any update on this PR?

**Comment by klavs** [comment]
This PR is welcome. Please fix the problems indicated by the CI.

**Comment by codiyer** [comment]
Well the problem here is that we are restricted by the version of `built_value_generator`. The current version of that package depends on ^0.39.3, because of which we are not able to upgrade this dependency. We can override the dependency but I don't think thats a good option though. I think we will have to wait till `build_value_generator` is updated. However, I am relatively new to this so I maybe wrong. I would appreciate if someone can let me know here.

**Comment by klavs** [comment]
Thanks for the context. I think there's another package in this repo which uses the older analyzer version. I had the impression that it was the cause.

**Comment by codiyer** [comment]
> Thanks for the context. I think there's another package in this repo which uses the older analyzer version. I had the impression that it was the cause.

There are 2 packages in this repo which have analyzer dependency, one is the `gql_code_builder` and another is `gql_build`. 
This PR is makes change only to the `pubspec.yaml` of `gql_code_builder`. I have updated both the files locally but stuck because of `built_value_generator`

**Comment by lucaspal** [comment]
I merged the latest master into my branch and I will have a look at the issues identified from the CI (a.k.a. I will try to bump the analyzer version in all places inside this repo).

Relating to what you mentioned @codiyer - from what I can see [here](https://github.com/google/built_value.dart/blob/d10058d1426fb5be8c100e2bd96b1094cab86c36/built_value_generator/pubspec.yaml#L12) the latest version of `built_value_generator` depends on the version we need of the analyzer. 

I only had a very quick look and I might have missed something but we might solve the issue bumping the version of that package.

**Comment by codiyer** [comment]
> I merged the latest master into my branch and I will have a look at the issues identified from the CI (a.k.a. I will try to bump the analyzer version in all places inside this repo).
> 
> Relating to what you mentioned @codiyer - from what I can see [here](https://github.com/google/built_value.dart/blob/d10058d1426fb5be8c100e2bd96b1094cab86c36/built_value_generator/pubspec.yaml#L12) the latest version of `built_value_generator` depends on the version we need of the analyzer.
> 
> I only had a very quick look and I might have missed something but we might solve the issue bumping the version of that package.

The `pubspec.yaml` that you are seeing [here](https://github.com/google/built_value.dart/blob/master/built_value_generator/pubspec.yaml) is of version `8.0.0-nullsafety.0` which has not been released yet in `pub.dev`and the PR notes in that latest commit of the file states that it is not yet ready. So I don't think we will be able to bump up the version of `built_value_generator` yet.

**Comment by lucaspal** [comment]
> > I merged the latest master into my branch and I will have a look at the issues identified from the CI (a.k.a. I will try to bump the analyzer version in all places inside this repo).
> > Relating to what you mentioned @codiyer - from what I can see [here](https://github.com/google/built_value.dart/blob/d10058d1426fb5be8c100e2bd96b1094cab86c36/built_value_generator/pubspec.yaml#L12) the latest version of `built_value_generator` depends on the version we need of the analyzer.
> > I only had a very quick look and I might have missed something but we might solve the issue bumping the version of that package.
> 
> The `pubspec.yaml` that you are seeing [here](https://github.com/google/built_value.dart/blob/master/built_value_generator/pubspec.yaml) is of version `8.0.0-nullsafety.0` which has not been released yet in `pub.dev`and the PR notes in that latest commit of the file states that it is not yet ready. So I don't think we will be able to bump up the version of `built_value_generator` yet.

@codiyer You are totally right - it is also quite explicit `Release 8.0.0-nullsafety.0 built_value, not ready for built_value_generator yet.`.

My guess is that we might as well wait for the NNBD release that would probably depend on something like `  analyzer: ^0.40.4` (like we did for `built_value`).


I will push my local changes and make this PR a draft, or will consider asking to set a blocked tag to it.
If you have any other idea, or you would like to try with dependecies override feel free. :smiley:

**Comment by codiyer** [comment]
> > > I merged the latest master into my branch and I will have a look at the issues identified from the CI (a.k.a. I will try to bump the analyzer version in all places inside this repo).
> > > Relating to what you mentioned @codiyer - from what I can see [here](https://github.com/google/built_value.dart/blob/d10058d1426fb5be8c100e2bd96b1094cab86c36/built_value_generator/pubspec.yaml#L12) the latest version of `built_value_generator` depends on the version we need of the analyzer.
> > > I only had a very quick look and I might have missed something but we might solve the issue bumping the version of that package.
> > 
> > 
> > The `pubspec.yaml` that you are seeing [here](https://github.com/google/built_value.dart/blob/master/built_value_generator/pubspec.yaml) is of version `8.0.0-nullsafety.0` which has not been released yet in `pub.dev`and the PR notes in that latest commit of the file states that it is not yet ready. So I don't think we will be able to bump up the version of `built_value_generator` yet.
> 
> @codiyer You are totally right - it is also quite explicit `Release 8.0.0-nullsafety.0 built_value, not ready for built_value_generator yet.`.
> 
> My guess is that we might as well wait for the NNBD release that would probably depend on something like ` analyzer: ^0.40.4` (like we did for `built_value`).
> 
> I will push my local changes and make this PR a draft, or will consider asking to set a blocked tag to it.
> If you have any other idea, or you would like to try with dependecies override feel free. 😃
> 
> @klavs Could you add a blocked label to this PR?

I don't think dependency override will work since there is this [issue](https://github.com/google/built_value.dart/issues/941) which is open. Dependency override does solve the issue of resolving the dependencies, but I think it's safe to assume that it's going to cause another set of issues.

**Comment by tc** [comment]
Any possibility to update the dependency of analyzer to ^3.0?

**Comment by tc** [comment]
looks like built_value was updated, can we update this package as well now?
https://github.com/google/built_value.dart/pull/1106

**Comment by budde377** [comment]
Hi, I'm the maintainer of `graphql` and `graphql_codegen`. We'll also be very interested in an updated version of this!

**Comment by agent3bood** [comment]
Closing PR as it is outdated.
Analyzer 3 is supported now https://github.com/gql-dart/gql/pull/298

**Pull request closed without merging**
