### PR TITLE
bump analyzer 2.2.0

### PR DESCRIPTION
**Pull request by vasilich6107**
Hi @smkhalsa I'm pingin you cause you was the last who contributed to `gql_code_builder`
I'm helping @comigor to maintain `artemis`

We would like to update our deps to latest version but we cannot due to `analyzer: 1.2.0` dep in `gql_code_builder`

I made this PR to update `ananlyzer` to latest version.

I also added some fixes for failing actions - mostly dependency reordering.

I would appreciate if you merge and release my PR.

Thanks

### CODE REVIEW

**Comment by vasilich6107** [comment]
@klavs may be you could review this PR?

**Comment by smkhalsa** [comment]
@vasilich6107 can you run a pubspec clean with multipack to fix the CI errors?

**Comment by vasilich6107** [comment]
thanks @smkhalsa for your support.
I ran the `multipack` command to resolve issues.
Some of them where resolved and some not.

I'm completely lost why github action demands me to sort dependancies in `gql_example_build` while they are sorted...

**Comment by smkhalsa** [comment]
@vasilich6107 an alpha release should be published automatically with these changes.

**Comment by vasilich6107** [comment]
Hi @smkhalsa 
I would like to request more help from you.

It is true that `gql_code_builder` where released 28 Sep.
The issue is it depends on `gql: 0.13.1-alpha+1632808907128` but there is no corresponding version of `gql` on `pub.dev`

In the meantime the `gql_exec: ^0.3.1-alpha+1632808907137` dependacy where successfuly released yesterday.

Could you help with missing `gql: 0.13.1-alpha+1632808907128`?

**Comment by smkhalsa** [comment]
Hmm, that's odd. I didn't set up the alpha release workflow, so I'm not sure why this could be happening. 

I'm traveling at the moment, so I likely won't be able to look into this until next week, but maybe one of the other maintainers has some insight.

**Comment by vasilich6107** [comment]
@smkhalsa do you know some who setted up the alpha release flow?

**Comment by vasilich6107** [comment]
@klavs I saw you were adjusting the flow
https://github.com/gql-dart/gql/commit/092db3e39178959093bab866351d49e62123a4e0

Could you help us?

**Comment by vasilich6107** [comment]
As you can see from the screenshot - all packages were updated on 28 Sep except `gql`

image

**Comment by vasilich6107** [comment]
@agent3bood may be you will be able to help with issue of non-relased `gql`?

**Comment by agent3bood** [comment]
@vasilich6107 The build/release script need some reworking, at the moment can you just use direct git url for the version you need?

https://flutter.dev/docs/development/packages-and-plugins/using-packages#dependencies-on-unpublished-packages

**Comment by vasilich6107** [comment]
@agent3bood thanks for quick response.
Unfortunately the direct git dependency is not an option - pub.dev does not allow to publish packages with overridden dependencies. I was doing this PR to unblock `atremis` package from `json_serializable` update.

**Comment by vasilich6107** [comment]
Ok. Let's try one more time)
May be @micimize or @TarekkMA could help me with this release issue?

**Comment by TarekkMA** [comment]
I don't know what is `cats` and why it's located in source files rather than test files.

We can extract it to another separate package. It doesn't seem to have a dependency on `gql` files.

Also, we can add it to `.pubignore` file, if it's not intended to be exported.

**Comment by TarekkMA** [comment]
@vasilich6107 `gql: ^0.13.1-alpha+1633799193898` is now publish on pub. 🥳

**Pull request merged**
