### PR TITLE
fix: Upgrade `gql_code_builder` for `gql_build`

### PR DESCRIPTION
**Pull request by ValentinVignal**
Fixes https://github.com/gql-dart/gql/issues/341

### CODE REVIEW

**Comment by knaeckeKami** [comment]
thanks! could you bump the gql_build version to 0.5.0? it's not a patch release since gql_code_builder 0.5 has breaking changes

**Comment by knaeckeKami** [comment]
also, please make sure that

`multipack --only gql_build pubspec clean` does not cause any changes to pubspec.yaml 

(I think you introduced some whitespace changes in the dependencies: line)

**Comment by ValentinVignal** [comment]
@knaeckeKami I changed the number version in https://github.com/gql-dart/gql/pull/342/commits/b451690ac1e088e7712db444004cb45678835bcf and cleaned the `pubspec.yaml` file in https://github.com/gql-dart/gql/pull/342/commits/f487ab47458775a1849117693ae33517d479eba6 (sorry for that, I had the auto-format on on my editor

**Comment by knaeckeKami** [comment]
Thanks!

**Pull request merged**
