### PR TITLE
[dio link] Add support for file upload

### LINKED ISSUE #169: [gql_dio_link] Upload Mutation doesn't work
I'm using gql_dio_link and graphql_flutter v4 because I need interceptor for manage auth cookie with CookieManager like this :     

```dart
dio.interceptors.add(CookieManager(CookieJar()));
```

I got this error during mutation call for upload file : 
```dart
flutter: *** DioError ***:
flutter: uri: http://localhost:4000/graphql
flutter: DioError [DioErrorType.DEFAULT]: Converting object to an encodable object failed: Instance of 'MultipartFile'
#0      _JsonStringifier.writeObject (dart:convert/json.dart:687:7)
#1      _JsonStringifier.writeMap (dart:convert/json.dart:768:7)
#2      _JsonStringifier.writeJsonValue (dart:convert/json.dart:723:21)
#3      _JsonStringifier.writeObject (dart:convert/json.dart:678:9)
#4      _JsonStringifier.writeMap (dart:convert/json.dart:768:7)
#5      _JsonStringifier.writeJsonValue (dart:convert/json.dart:723:21)
#6      _JsonStringifier.writeObject (dart:convert/json.dart:678:9)
#7      _JsonStringStringifier.printOn (dart:convert/json.dart:876:17)
#8      _JsonStringStringifier.stringify (dart:convert/json.dart:861:5)
#9      JsonEncoder.convert (dart:convert/json.dart:261:30)
#10     JsonCodec.encode (dart:convert/json.dart:171:45)
#11     DefaultTransformer.transformRequest (package:dio/src/transformer.dart:62:21)
#12     DioMixin._transformData (package:dio/src/dio.dart:1014:39)
<…>
```

Here is my graphql client : 
```dart
  final Link link = DioLink(
      '${DotEnv().env['BASE_URL']}/graphql',
      client: httpService.dio,
    );
    client = GraphQLClient(
      cache: GraphQLCache(),
      link: link,
    );
``` 

Mutation : 
```dart
const String uploadFile = """
  mutation uploadRequestedFile(\$requestedFileId: ID!, \$file: Upload!) {
    uploadRequestedFile(requestedFileId: \$requestedFileId, file: \$file) {
      id
      documentUrl
    }
  }
""";
```
```dart
    final QueryResult result = await graphqlService.client.mutate(
      MutationOptions(
        document: gql(uploadFile),
        variables: {
          'file': await imagePickerService.multipartFileFrom(document.file),
          'requestedFileId': document.id,
        },
      ),
    );
```

This problem occurs when serializing the body http.
Therefore i checked HttpLink source code, and here is how httpLink handles this case :
```dart
    final httpBody = _encodeAttempter(
      request,
      (Map body) => json.encode(
        body,
        toEncodable: (dynamic object) =>
            (object is http.MultipartFile) ? null : object.toJson(),
      ),
    )(body);
```

### PR DESCRIPTION
**Pull request by TarekkMA**
now dio_link should be able to handle `MultipartFile` files

Closes #169

### CODE REVIEW

**Comment by agent3bood** [comment]
Hi @TarekkMA 

Some tests are failing, is this something you can work on? 

1.  gql_code_builder
2. gql_example_cli_github
3. check_svg <<< ignore this test

**Comment by TarekkMA** [comment]
I will try to get them fixed.

**Comment by TarekkMA** [comment]
I was able to fix "gql_code_builder" with a re-run for the actions. I don't know why exactly is the diff check is failing for "gql_example_cli_github". My changes have nothing to do with code gen.

**Comment by agent3bood** [comment]
> My changes have nothing to do with code gen

I agree, please bump the version and I will merge it.

**Comment by agent3bood** [comment]
Also update the CHANGELOG.md please

**Comment by TarekkMA** [comment]
Okay done.

**Comment by kateile** [comment]
@TarekkMA I am trying to use this feature but I got error. 
Converting object to an encodable object failed: Instance of 'MultipartFile'

```
import 'package:dio/dio.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:gallery_saver/gallery_saver.dart';
import 'package:http_parser/http_parser.dart';
import 'package:image_cropper/image_cropper.dart';
import 'package:image_picker/image_picker.dart';
import 'package:mime/mime.dart';
```

```dart
            final mimeType = lookupMimeType(cropped.path);

            final bytes = await cropped.readAsBytes();

            final file = await MultipartFile.fromBytes(
              bytes,
              filename: cropped.path.split('/').last,
              contentType: MediaType(
                mimeType.split('/').first,
                mimeType.split('/').last,
              ),
            );

            cubit.uploadAvatar(
              UploadAvatarArguments(
                input: file,
              ),
            );
```

same code use to work with **gql_http_link** upload together with http.MultipartFile now I am trying to use using dio.MultipartFile and glq_dio_link. 
I am using artemis for code generation too
any hints on how to solve this?

**Comment by TarekkMA** [comment]
I do have test to check that `dio.MultipartFile` is encoded correctly. ("request encoding" test in multipart_upload_test.dart)

These are some pointer that may help you to solve this:
1. make sure you are using the alpha version not the current stable one
2. only `dio.MultipartFile` will work so make sure you are using that not `http.MultipartFile`

**Comment by kateile** [comment]
I am using `gql_dio_link: ^0.2.1-alpha+1628192550872` as well as `dio.MultipartFile`. I will try to reproduce it in demo project

**Comment by TarekkMA** [comment]
Thank you, when you have the demo project ready please open up a new issue.

**Comment by kateile** [comment]
@TarekkMA [here](https://github.com/kateile/gql_dio_link_upload_tester) is the reproductive app showing the described bug.

**Pull request merged**
