### PR TITLE
nullsafety/gql-code-builder-packages-update

### PR DESCRIPTION
**Pull request by vasilich6107**
Updated 
- `build_runner`
- `code_builder`

### CODE REVIEW

**Comment by vasilich6107** [comment]
For those who blocked I released https://pub.dev/packages/gql_code_builder_temp

**Comment by micimize** [comment]
looks like https://github.com/gql-dart/gql/pull/221 addressed this also

**Comment by agent3bood** [comment]
> looks like #221 addressed this also

I have used the branch from #221 and it looks fine so far (app is still in development).


```
dependency_overrides:
  # keep this until gql libraries are updated
  gql_code_builder:
    git:
      url: git@github.com:gql-dart/gql.git
      ref: codegen-nullsafety
      path: codegen/gql_code_builder
  gql_build:
    git:
      url: git@github.com:gql-dart/gql.git
      ref: codegen-nullsafety
      path: codegen/gql_build
  code_builder: ^4.0.0
  built_value_generator: ^8.0.5
  source_gen: ^1.0.0
  build_config: ^1.0.0
#    end gql issue
```

**Comment by micimize** [comment]
Ok – I'm gunna close this for now then, and merge+publish nullsafety packages

**Pull request closed without merging**
