### PR TITLE
gql_dio_link: Forward original exception on dio errors

### PR DESCRIPTION
**Pull request by jamonkko**
Pass original exception also if http request fails with error status. Dio throws DioError if response status is in error range so this makes it possible to have that as original error and makes debugging easier.

### CODE REVIEW

**Review by agent3bood — COMMENTED** [review]
LGTM

**Comment by agent3bood** [comment]
Thanks for contributing to this library.

Please bump the package version and add a line in CHANGELOG

**Comment by jamonkko** [comment]
Version and changelog updated.

**Review by agent3bood — APPROVED** [review]

**Comment by jamonkko** [comment]
@agent3bood Thank you (and all other maintainers) for doing this work! Really appreciate this library.

**Pull request merged**
