### PR TITLE
support analyzer ^3.0.0

### PR DESCRIPTION
**Pull request by knaeckeKami**

### CODE REVIEW

**Comment by agent3bood** [comment]
Hi @knaeckeKami 

Thanks for the PR, I am looking at [Analyzer 3.0.0](https://pub.dev/packages/analyzer/changelog#300), and it did remove many deprecated functions. So I am not sure supporting 2 major versions will work `analyzer: '>=2.3.0 <4.0.0'`.

**Comment by agent3bood** [comment]
> I have to check if I can get the exact required version of graphviz installed on my mac machine, it seems brew only has newer versions unfortunately
Never mind  the svg check, it has been failing for some time now!

**Comment by knaeckeKami** [comment]
Ok, well I think this is ready then!

**Comment by agent3bood** [comment]
Please change the package version to `version: 0.5.0` and add an entry to CHANGELOG.

**Review by agent3bood — APPROVED** [review]

**Comment by budde377** [comment]
@agent3bood thank you for this! When are you expecting to release it to pub?

**Comment by agent3bood** [comment]
> @agent3bood thank you for this! When are you expecting to release it to pub?

@klavs Can you upgrade from alpha release?

**Comment by knaeckeKami** [comment]
if you are using a ferry, you probably cannot upgrade yet. I think there is an issue with ferry_generator, (the serializer for FetchPolicy might not be imported correctly ).

I probably cannot look into it in the next few days, but I think the fix should be trivial.

**Comment by agent3bood** [comment]
I will try to solve this tomorrow as we need it for a project, just to same me some time are there other packages need upgrading?

**Comment by klavs** [comment]
@agent3bood, please check my message on discord.

**Pull request merged**
