### PR TITLE
Add websocket link

### PR DESCRIPTION
**Pull request by agent3bood**
Related issues:
https://github.com/gql-dart/gql/issues/76
https://github.com/comigor/artemis/issues/76
https://github.com/zino-app/graphql-flutter/issues/608

### CODE REVIEW

**Comment by klavs** [comment]
@agent3bood thanks for the contribution!

As a heads-up, here are two things you'll need to do:
- add the package to the workflow https://github.com/gql-dart/gql/blob/master/.github/workflows/dart.yml
- use the gql_pedantic rules https://github.com/gql-dart/gql/blob/master/gql_link/analysis_options.yaml

**Comment by klavs** [comment]
@agent3bood, #97 by @iscriptology got ahead of you. Could you please review #97 to see if it covers what you ported?

**Comment by agent3bood** [comment]
@klavs 
I have seen the pr by @iscriptology here are the things that are in my PR and not in the other, please give us feedback, I will be happy to contribute to wither PRs.

The main difference is I used https://pub.dev/packages/web_socket_channel as a base for the connection, in PR 97 is is using https://pub.dev/packages/websocket and implementing custom client. (Need feedback on this, what is better?)

Best
Abdullah

**Comment by klavs** [comment]
@agent3bood, I would actually prefer `web_socket_channel`. Could you rebase/redo this change on top of @iscriptology 's branch?
#97 seems quite ready for an alpha release and I'll try to merge it within 24 hours.

**Comment by agent3bood** [comment]
ok, I will send a PR to @iscriptology with the `web_socket_channel`, but tests will be in another day :(

**Comment by klavs** [comment]
You do not have to rush. Just base your branch on he's and we'll merge it to `master` (of this repo) later.

**Comment by agent3bood** [comment]
Closing, all implementation is now moved to WSLink

**Comment by iscriptology** [comment]
What is the roadmap for stabilization of the websocket link?
I offer my help if needed.
Besides, the latest alpha version currently relies on alpha releases of different gql packages. why?

**Pull request closed without merging**
